### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by searcy** [archivesspace/tech-docs#156]
There are a handful of links in the GitHub repository that resolve to 404 errors (e.g., [Theming ArchivesSpace](https://github.com/archivesspace/tech-docs/blob/master/customization/theming.html)) but that do display in the .io site: https://archivesspace.github.io/tech-docs/customization/theming.html

**Comment by crugas** [comment]
So does the README file link found in the plugins page: https://github.com/archivesspace/tech-docs/blob/174f397372ee41d0c6ca9db6a9fcd4a8f2c7c909/customization/plugins.md?plain=1#L10

It should be this: https://github.com/archivesspace/archivesspace/blob/master/plugins/hello_world/README.md

**Comment by brianzelip** [comment]
@crugas - good catch, that link was changed assuming it was a local page for tech docs, but it is actually an external link.

@searcy - is there a link somewhere pointing to https://github.com/archivesspace/tech-docs/blob/master/customization/theming.html? Because all the links I found on the published site that should point to the published 'Theming AS' page, do in fact point to https://archivesspace.github.io/tech-docs/customization/theming.html.

**Comment by searcy** [comment]
@brianzelip It looks like it's been addressed, so nevermind, I guess! I think a bunch of links within GitHub at one point ended in .html instead of .md and the html links did not work, but it looks like things are good now.

**Comment by brianzelip** [comment]
@crugas want to make a PR with your solution to fix the issue in the source code? If so feel free to reach out with any questions you might have.

**Comment by crugas** [comment]
@brianzelip Just created a PR here: https://github.com/archivesspace/tech-docs/pull/159. Lmk if there's anything I need to correct/redo.

**Comment by searcy** [comment]
Thanks @brianzelip and @crugas -- I'm going to close this issue.
